# Generated by Django 4.1.2 on 2022-10-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset_transport_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_req', models.CharField(max_length=10)),
                ('from_req', models.CharField(max_length=150)),
                ('to_req', models.CharField(max_length=150)),
                ('date_time_req', models.DateTimeField()),
                ('is_flex_req', models.BooleanField(default=False)),
                ('quantity_req', models.IntegerField()),
                ('asset_type', models.CharField(max_length=20)),
                ('asset_type_sensitivity', models.CharField(max_length=20)),
                ('deliver', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='rider_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rider', models.CharField(max_length=10)),
                ('from_rider', models.CharField(max_length=150)),
                ('to_rider', models.CharField(max_length=150)),
                ('date_time_rider', models.DateTimeField()),
                ('is_flex_rider', models.BooleanField(default=False)),
                ('medium_rider', models.CharField(max_length=20)),
                ('quantity_rider', models.IntegerField()),
            ],
        ),
    ]
